# CryptoWolf Default Config

title = "CryptoWolf"

[base]
folder = "CryptoWolf"
static = "./build/frontend/"
expectRateBound = 0.1
debug = false

[blockchain]
type = "ethereum"
blockchainId = 'F000003C'
factoryContractAddress = ''
routerContractAddress = ''
token0Address = ''
token1Address = ''

[database]
type = "firebase"

[tidewalletjs]
apiURL = 'https://staging.tidewallet.io/api/v1'
apiKey = ''
apiSecret = ''
thirdPartyId = 'myAppleID'
installId = 'myInstallID'
debugMode = true
networkPublish = false

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo"
]