# CryptoWolf Default Config

title = "CryptoWolf"

[base]
folder = "CryptoWolf"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[tokenPair]
firstTokenAddress = ''
secondTokenAddress = ''

[tidewalletjs]
apiURL = 'https://staging.tidewallet.io/api/v1'
apiKey = ''
apiSecret = ''
thirdPartyId = 'myAppleID'
installId = 'myInstallID'
debugMode = true
networkPublish = false

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo"
]